[build]
  command = "npm run build:web"
  publish = "web-build"

[context.production.environment]
SUPABASE_URL=https://lcgmghfzwgznagppufux.supabase.co
SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjZ21naGZ6d2d6bmFncHB1ZnV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NzI0MjksImV4cCI6MjA2NDE0ODQyOX0.e-ejeHeq_L8aUHfVwrBLHr-xMdt68jXiQFoY70XQNCA

[context.deploy-preview]
  command = "npm run build:web"
  publish = "web-build"

[context.branch-deploy]
  command = "npm run build:web"
  publish = "web-build"
